spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: allosh
    password: allosh
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.allosh.ecommerce.kafka.orderConfirmation

server:
  port: 8070

application:
  config:
    product-url: http://localhost:8222/api/v1/products
    customer-url: http://localhost:8222/api/v1/customers
    payment-url: http://localhost:8222/api/v1/payments

