spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: allosh
    password: allosh
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.allosh.ecommerce.payment.paymentConfirmation

server:
  port: 8060


